# -*- coding: utf-8 -*-
"""Aula3Sub.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_TxLh3XPtQgQMdeYNj5Zf_tSFP0yeMXw
"""

# ETE PORTO DIGITAL 
# DISCIPLINA: LPC1
# PROFESSOR: CLOVES
# ESTUDANTE: PRAXEDES

print ("Olá, ETE PORTO DIGITAL!")